### ISSUE TITLE
Getting cookie on mobile

### ISSUE THREAD

**Issue by niss1m** [rtunazzz/hidemyemail-generator#1]
I don't own a mac can I still get my cookie?

**Comment by rtunazzz** [comment]
Hey, yes. You don't need a Mac but you do need a computer. Windows/Linux will work just fine

**Comment by niss1m** [comment]
Yeah I won't mind running it on windows/linux, how can I do that though?

**Comment by rtunazzz** [comment]
There's a [step by step guide](https://github.com/rtunazzz/hidemyemail-generator#setup) on how to set things up in the readme. Just do that and you should be good to go.

On Windows, you can download the Windows binary from the [releases page](https://github.com/rtunazzz/hidemyemail-generator/releases/tag/v0.01) and run that without installing Python.
