### ISSUE TITLE
cookie.txt not found

### ISSUE THREAD

**Issue by Danielhighfive** [rtunazzz/hidemyemail-generator#11]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/47258814/224487377-1ae2be84-4d85-4c84-9fae-2b308e059e84.png">
<img width="724" alt="image" src="https://user-images.githubusercontent.com/47258814/224487405-5c1fb678-05ef-46c7-aae9-f4e124e84a17.png">

I have the issue that the cookie.txt is not found even tho it is in the same directory

**Comment by Danielhighfive** [comment]
Building the project myself instead of using the prebuild binaries resolved the issue

**Comment by rtunazzz** [comment]
Interesting @Danielhighfive, thanks for the heads up! Glad you got it sorted out.
