### ISSUE TITLE
Error to create one account

### ISSUE THREAD

**Issue by Sonklol** [rtunazzz/hidemyemail-generator#18]
![imagen](https://github.com/rtunazzz/hidemyemail-generator/assets/64712212/d809a98f-ad80-4ef6-8470-aded69cd3397)

**Comment by rtunazzz** [comment]
Hi @Sonklol, what's the purpose of this raised issue?

I see it clearly stated in the screenshot why it doesn't generate.

My guess would be that it doesn't let you create emails manually on the web either. Do you have an active iCloud+ subscription?
---
If that's not the case, I'll need more details about your issue. Pull requests are always welcome as well 😉

**Comment by Sonklol** [comment]
No, I don't have an iCloud+ subscription. It is necessary?

**Comment by rtunazzz** [comment]
Yes.

https://github.com/rtunazzz/hidemyemail-generator/blob/0534cc347e525d291cde78cf2a0d372b931c37e1/README.md?plain=1#L5
