### ISSUE TITLE
Please why is this issue

### ISSUE THREAD

**Issue by updatelogs** [rtunazzz/hidemyemail-generator#19]
How many iCloud emails you want to generate?: 5
[01:53:28] Generating 5 email(s)...                                                                          main.py:94
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[01:53:29] [ERR] - Failed to generate email. Reason: Invalid global session                                  main.py:48
           [ERR] - Failed to generate email. Reason: Invalid global session                                  main.py:48
           [ERR] - Failed to generate email. Reason: Invalid global session                                  main.py:48
           [ERR] - Failed to generate email. Reason: Invalid global session                                  main.py:48
           [ERR] - Failed to generate email. Reason: Invalid global session                                  main.py:48

**Comment by rtunazzz** [comment]
Hi @updatelogs,

Seems like your session cookie is malformed. Try re-copying it and see if that helps
