### ISSUE TITLE
Program closing in few seconds .

### ISSUE THREAD

**Issue by macfarlanechristal** [rtunazzz/hidemyemail-generator#21]
When i just downloaded that like 2 weeks ago all was good. Was genering like 20 accs every 30 min and saying at the end how many accounts was generated. 

But since last week or something like that every time when i start its just closing in around few seconds without saying about any result, still genering some accs, but ig like 2-3 of them good

**Comment by macfarlanechristal** [comment]
I tried to copy new cookie again, nothing changed

**Comment by macfarlanechristal** [comment]
Oh, if i run through cmd all good as before. Just for example its saying 15 mails generated , but 50% of them just copy of another one

**Comment by rtunazzz** [comment]
Hi @macfarlanechristal,

The registration works in 2 steps - first it generates the email (shown as 50% on the CLI), then it has to reserve it (shown as 100%). The email is not usable without a successful registration.

Duplicates in the first step don't really matter, because the email still needs to be reserved, which should fail if the email is already taken (reserved)

**Comment by rtunazzz** [comment]
So it shouldn't actually save the duplicates into the output file

**Comment by macfarlanechristal** [comment]
> So it shouldn't actually save the duplicates into the output file

But its saving, as i saying like 80% of generated are duplicates

**Comment by macfarlanechristal** [comment]
![image](https://github.com/rtunazzz/hidemyemail-generator/assets/137405388/2bbbf055-a89a-41c2-a379-236e127ae015)
Like this

**Comment by macfarlanechristal** [comment]
@rtunazzz like this 
![image](https://github.com/rtunazzz/hidemyemail-generator/assets/137405388/25cde3c4-f70b-433f-adfd-dd5f027fbd99)

**Comment by rtunazzz** [comment]
Closing this, please open a new issue with the duplication if you're still facing it. Thanks!
