### ISSUE TITLE
Error main.py:48

### ISSUE THREAD

**Issue by vnmlike** [rtunazzz/hidemyemail-generator#24]
[04:10:56] [ERR] - Failed to generate email. Reason: 0, message='Attempt to decode JSON with unexpected      main.py:48
           mimetype: ', url=URL('https://p68-maildomainws.icloud.com/v1/hme/generate?clientBuildNumber=2317P
           roject38&clientMasteringNumber=2317B22&clientId=&dsid=')

i am quite sure i have done it right

logging into icloud.com with my regular account
(no vpn on, no nothing on!)
then export cookies, of course i made sure i changed the preferred format in the settings to:
semicolon....valvue pairs.

i thought before that maybe it was because i chose this browser confidentially, but no, that wasn't it either

I was so happy to have found this tool.

**Comment by rtunazzz** [comment]
Hi, pull latest from main, this should be fixed in PR #22 🫡

**Comment by rtunazzz** [comment]
Hi!

Looks related to what I was seeing with listing emails. Probably related to #22 (new v2 endpoints going live)

Feel free to make the change yourself and submit a PR, or I will when I get to it

**Comment by vnmlike** [comment]
after changes:
C:\Users\PC\hidemyemail-generator>python main.py
Traceback (most recent call last):
  File "C:\Users\PC\hidemyemail-generator\main.py", line 12, in <module>
    from icloud import HideMyEmail
  File "C:\Users\PC\hidemyemail-generator\icloud\__init__.py", line 1, in <module>
    from .hidemyemail import HideMyEmail
  File "C:\Users\PC\hidemyemail-generator\icloud\hidemyemail.py", line 9
    base_url_v2 = "https://p68-maildomainws.icloud.com/v2/hme"
                                                              ^
IndentationError: unindent does not match any outer indentation level

**Comment by rtunazzz** [comment]
Looks like you wrongly indented the `base_url_v2` @vnmlike.

Oddly enough though, the V1 endpoint is working just fine for me for generating emails... 🤔

**Comment by vnmlike** [comment]
what i must do?

**Comment by rtunazzz** [comment]
Closing this in favor of #26, since it's the same issue
