### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by Obalogunlion** [rtunazzz/hidemyemail-generator#25]
Nice concept but please how do we get the password for the generated emails because the password for my appleID is not working for it or I dont need to try to login if I use it as smtp it will work?
thanks :)

**Comment by rtunazzz** [comment]
Hi @Obalogunlion!

There is no password for the generated emails.

They are all forwarded (by Apple) to your main iCloud email (or whatever you set it to in your iCloud+ settings)

**Comment by Obalogunlion** [comment]
how's is possible for me to use it as smtp?
any heads up?

**Comment by rtunazzz** [comment]
Wdym use it as SMTP?

All emails will get forwarded to your main email. You can then use that main email for whatever use you need.
