### ISSUE TITLE
Failed to generate email. Reason: Invalid session

### ISSUE THREAD

**Issue by Someone3731** [rtunazzz/hidemyemail-generator#5]
Why I have this error?
I think my cookies are correct

**Comment by rtunazzz** [comment]
Log into iCloud again and replace the cookie with a new one, this usually happens when your session expires

**Comment by Someone3731** [comment]
Already tried and didn't work
I need to be logged on my Apple account?
If yes, the account need to be created on apple device?

**Comment by rtunazzz** [comment]
It works fine for me, so you aren't doing something correctly :)

I'd first double-check you're fully logged into your iCloud account at <https://www.icloud.com/> and make sure you're pasting the cookies in a correct (semicolon separated key=value) format, without any comments.

If that still doesn't work for you, feel free to reopen the issue with details so I can replicate it or I'd be more than happy if you fixed the issue and contributed to the repository!

**Comment by Someone3731** [comment]
I don't have any apple device, do you think it's the problem?
If yes, could you send me an apple account who is create on phone please?
For better communication, can you told me your time zone and your Telegram,
Messenger or any other social network where you is active please?

**Comment by rtunazzz** [comment]
Sure @Someone3731! I'm on EU time, twitter - @rtunazzz

**Comment by Someone3731** [comment]
I have already contact you but you don't answer my messages, even if yoj
see them

**Comment by rtunazzz** [comment]
Hi @yoKurt94,

Seems like that's something on your end unfortunately.

AFAIK you need yo have iCloud+ for the generation to work but as soon as the generation is working fine via iCloud UI (https://www.icloud.com/icloudplus/), then you should be good.

If that doesn't help, try double checking your cookie.txt file. That's usually another common issue people face.

**Comment by yoKurt94** [comment]
I didn't read that I need to have an iCloud+ Account, so I assume that this was the issue.

**Comment by Foxtrod89** [comment]
> Hi [@yoKurt94](https://github.com/yoKurt94),
> 
> Seems like that's something on your end unfortunately.
> 
> AFAIK you need yo have iCloud+ for the generation to work but as soon as the generation is working fine via iCloud UI (https://www.icloud.com/icloudplus/), then you should be good.
> 
> If that doesn't help, try double checking your cookie.txt file. That's usually another common issue people face.

Unfortunately I faced same issue, to fix that I have to regenerate cookies from scratch. Would be great if you address this accordingly.
