### ISSUE TITLE
Cannot Run

### ISSUE THREAD

**Issue by peezysoles** [rtunazzz/hidemyemail-generator#6]
Hello,

I am having troubles trying to run this, since I do not know much about running code through Python. I downloaded the windows files and tried extracting all of it from the .zip, but the main application seems to disappear.

Do you have discord by any chance or server for this program for guides and such?

Thank you!

**Comment by peezysoles** [comment]
Nevermind, I found my antivirus kept removing it! Silly mistake I made!

**Comment by rtunazzz** [comment]
Hi @peezysoles! Glad you got it sorted out :)

Just FYI, you can also download the prebuilt executables from the [releases page ](https://github.com/rtunazzz/hidemyemail-generator/releases) so you wouldn't have to install Python at all!
